const screens=['screen-form','screen-confirm','screen-received','screen-thanks','screen-consult','screen-found','screen-edit'];
const state={name:'',phone:'',email:'',people:'',date:'',time:'',notes:'',code:''};
window.state=state;
const $=id=>document.getElementById(id);
const API=()=>window.CAMBORIO_CONFIG?.publicReservationsFunction||'https://caeszgtogifserrxdrcw.supabase.co/functions/v1/public-reservas';
const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const parseISO=v=>{const [y,m,d]=String(v||'').split('-').map(Number);return y&&m&&d?new Date(y,m-1,d):null};
const isoDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const displayDate=v=>{const d=parseISO(v);return d?d.toLocaleDateString('es-ES',{day:'2-digit',month:'2-digit',year:'numeric'}):''};
const isMonday=v=>{const d=parseISO(v);return d?.getDay()===1};
function showScreen(id){screens.forEach(s=>$(s)?.classList.toggle('active',s===id));window.scrollTo({top:0,behavior:'smooth'})}
function formatDate(v){return displayDate(v)||'-'}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setDateField(id,v){const e=$(id);if(!e)return;e.dataset.iso=v||'';e.value=displayDate(v);e.classList.toggle('has-date',!!v)}
function openEmailModal(){$('email-modal').hidden=false;setTimeout(()=>$('email-send')?.focus(),50)}
function closeEmailModal(){$('email-modal').hidden=true}
function renderSummary(target='summary'){const rows=[['👤 Nombre',state.name],['📞 Teléfono',state.phone],['✉️ Email',state.email||'-'],['👥 Comensales',state.people],['📅 Fecha',formatDate(state.date)],['🕘 Hora',state.time],['📝 Observaciones',state.notes||'Sin observaciones']];$(target).innerHTML=rows.map(([l,v])=>`<div class="summary-row"><span class="summary-label">${l}</span><span class="summary-value">${escapeHtml(v||'-')}</span></div>`).join('')}
function ensureModal(){
 if($('app-modal'))return;
 const style=document.createElement('style');style.textContent=`#app-modal{position:fixed;inset:0;z-index:10000;display:none;align-items:center;justify-content:center;padding:20px;background:rgba(8,11,15,.74);backdrop-filter:blur(4px)}#app-modal.open{display:flex}#app-modal .app-modal-card{width:min(92vw,430px);background:#20252b;color:#f3f5f7;border:1px solid #3d4752;border-radius:24px;box-shadow:0 18px 60px rgba(0,0,0,.5);padding:25px 23px 20px;text-align:center}#app-modal .app-modal-icon{width:54px;height:54px;margin:0 auto 12px;border-radius:50%;display:grid;place-items:center;background:#2c343d;font-size:27px}#app-modal h2{margin:0 0 8px;font-size:21px}#app-modal p{margin:0;color:#b9c1ca;font-size:15px;line-height:1.5;white-space:pre-line}#app-modal .app-modal-actions{display:flex;justify-content:center;gap:10px;margin-top:20px}#app-modal button{border:0;border-radius:12px;min-height:44px;padding:0 20px;font-weight:800;font-size:14px}#app-modal-ok{background:#ffc928;color:#171a1d}#app-modal-cancel{background:#303840;color:#f3f5f7;border:1px solid #4a5560!important}.date-day.selected{outline:3px solid #2f6fed!important;outline-offset:1px;box-shadow:0 0 0 2px rgba(47,111,237,.18) inset!important;font-weight:900!important}.time-btn.selected{outline:2px solid #2f6fed;outline-offset:1px;font-weight:900}`;document.head.appendChild(style);
 const m=document.createElement('div');m.id='app-modal';m.innerHTML='<div class="app-modal-card" role="dialog" aria-modal="true"><div class="app-modal-icon" id="app-modal-icon">ℹ️</div><h2 id="app-modal-title">Información</h2><p id="app-modal-message"></p><div class="app-modal-actions"><button id="app-modal-cancel" type="button" hidden>CANCELAR</button><button id="app-modal-ok" type="button">ACEPTAR</button></div></div>';document.body.appendChild(m);
 let resolve=null;window.__camborioModal=(message,o={})=>{m.classList.add('open');$('app-modal-title').textContent=o.title||'Información';$('app-modal-icon').textContent=o.icon||'ℹ️';$('app-modal-message').textContent=String(message||'');$('app-modal-ok').textContent=o.ok||'ACEPTAR';$('app-modal-cancel').hidden=!o.confirm;return new Promise(r=>resolve=r)};
 $('app-modal-ok').onclick=()=>{const r=resolve;resolve=null;m.classList.remove('open');r?.(true)};$('app-modal-cancel').onclick=()=>{const r=resolve;resolve=null;m.classList.remove('open');r?.(false)};
 window.alert=message=>window.__camborioModal(message,{title:'Taberna Camborio',icon:'ℹ️'});
}
function info(message,o){ensureModal();return window.__camborioModal(message,o)}
let calendarTarget='date',calendarMonth=new Date();calendarMonth.setDate(1);
function moveDateModalInline(target){const modal=$('date-modal'),field=$(target),row=target==='date'?field.closest('.date-time-row'):field.closest('.grid-2');if(row&&row.parentNode)row.parentNode.insertBefore(modal,row.nextSibling);modal.dataset.calendarTarget=target}
function openDateModal(target){calendarTarget=target;moveDateModalInline(target);const current=$(target).dataset.iso||todayISO();const d=parseISO(current)||parseISO(todayISO());calendarMonth=new Date(d.getFullYear(),d.getMonth(),1);renderCalendar();$('date-modal').hidden=false}
function closeDateModal(){$('date-modal').hidden=true}
function renderCalendar(){const y=calendarMonth.getFullYear(),m=calendarMonth.getMonth();$('date-month').textContent=calendarMonth.toLocaleDateString('es-ES',{month:'long'}).replace(/^./,c=>c.toUpperCase());$('date-year').textContent=y;const grid=$('date-grid');grid.innerHTML='';const first=new Date(y,m,1),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),min=todayISO();for(let i=0;i<offset;i++){const e=document.createElement('span');e.className='date-empty';grid.appendChild(e)}for(let day=1;day<=days;day++){const d=new Date(y,m,day),iso=isoDate(d),b=document.createElement('button');b.type='button';b.className='date-day';b.textContent=day;if(iso<min){b.disabled=true;b.classList.add('disabled')}if(iso===$(calendarTarget).dataset.iso)b.classList.add('selected');if(iso===min)b.classList.add('today');b.onclick=()=>{if(isMonday(iso)){info('Los lunes cerramos por descanso del personal.',{title:'Día de descanso',icon:'🛌'});return}document.querySelectorAll('#date-grid .date-day.selected').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');setDateField(calendarTarget,iso);state.date=iso;state.time='';if($('selected-time'))$('selected-time').textContent='Selecciona una hora';$('time-trigger')?.classList.remove('has-time');if($('time-panel'))$('time-panel').hidden=true;if($('edit-selected-time'))$('edit-selected-time').textContent='Selecciona una hora';$('edit-time-trigger')?.classList.remove('has-time');if($('edit-time-panel'))$('edit-time-panel').hidden=true;setTimeout(closeDateModal,300)};grid.appendChild(b)}}
function changeMonth(delta){const next=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+delta,1),min=new Date(new Date().getFullYear(),new Date().getMonth(),1);if(next<min)return;calendarMonth=next;renderCalendar()}
async function getAvailability(date){const u=`${API()}?action=availability&date=${encodeURIComponent(date)}`;const r=await fetch(u,{cache:'no-store'});let d={};try{d=await r.json()}catch(_){}if(!r.ok||d.ok===false)throw new Error(d.error||'No se han podido consultar las horas disponibles.');return d.availability||{COMIDA:[],CENA:[]}}
function renderTimes(id,values,edit){const box=$(id);if(!box)return;box.innerHTML='';values.forEach(t=>{const b=document.createElement('button');b.type='button';b.className='time-btn';b.textContent=t;if(t===state.time)b.classList.add('selected');b.onclick=()=>{document.querySelectorAll(`#${edit?'edit-time-panel':'time-panel'} .time-btn`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');if(edit){state.time=t;$('edit-selected-time').textContent=t;$('edit-time-trigger').classList.add('has-time')}else{state.time=t;$('selected-time').textContent=t;$('time-trigger').classList.add('has-time')}setTimeout(()=>{const p=$(edit?'edit-time-panel':'time-panel');if(p)p.hidden=true},300)};box.appendChild(b)})}
function setShiftVisibility(edit,l,d){const lunchBlock=$(edit?'edit-lunch-block':'lunch-block'),dinnerBlock=$(edit?'edit-dinner-block':'dinner-block');if(lunchBlock)lunchBlock.hidden=!l.length;if(dinnerBlock)dinnerBlock.hidden=!d.length}
async function openTimes(edit=false){const field=$(edit?'edit-date':'date'),iso=field?.dataset.iso||'';if(!iso)return info('Primero selecciona una fecha.',{title:'Falta la fecha',icon:'📅'});if(isMonday(iso))return info('Los lunes cerramos por descanso del personal.',{title:'Día de descanso',icon:'🛌'});try{const a=await getAvailability(iso),l=a.COMIDA||[],d=a.CENA||[];renderTimes(edit?'edit-lunch-times':'lunch-times',l,edit);renderTimes(edit?'edit-dinner-times':'dinner-times',d,edit);setShiftVisibility(edit,l,d);const p=$(edit?'edit-time-panel':'time-panel');if(!l.length&&!d.length){p.hidden=false;return info('No quedan horas disponibles para ese día. Recuerda que la reserva debe hacerse con al menos una hora de antelación.',{title:'Sin disponibilidad',icon:'🕐'})}p.hidden=false}catch(e){info(e.message,{title:'No se pudo consultar',icon:'⚠️'})}}
function readForm(){state.name=$('name').value.trim();state.phone=$('phone').value.trim();state.email=$('email').value.trim();state.people=$('people').value;state.date=$('date').dataset.iso||'';state.notes=$('notes').value.trim()}
function validForm(){readForm();if(!state.name||!state.phone||!state.people||!state.date){$('reservation-form').reportValidity();return false}if(isMonday(state.date)){info('Los lunes cerramos por descanso del personal.',{title:'Día de descanso',icon:'🛌'});return false}if(!state.time){info('Selecciona una hora disponible antes de continuar.',{title:'Falta la hora',icon:'🕐'});return false}return true}
function fill(r){state.name=r.Nombre||'';state.phone=r.Telefono||'';state.email=r.Email||'';state.people=String(r.Personas||'');state.date=String(r.FechaReserva||'').slice(0,10);state.time=String(r.HoraReserva||'').slice(0,5);state.notes=r.Observaciones||'';state.code=r.CodigoReserva||'';$('edit-name').value=state.name;$('edit-phone').value=state.phone;$('edit-email').value=state.email;$('edit-people').value=state.people;$('edit-notes').value=state.notes;setDateField('edit-date',state.date);$('edit-selected-time').textContent=state.time;$('edit-time-trigger').classList.add('has-time');$('edit-code').textContent=state.code}
function buildReservationPdf(r){
 const created=r?.created_at||r?.CreadoEn||r?.FechaCreacion||'';
 const generated=new Date();
 const dateText=String(r?.FechaReserva||'').slice(0,10).split('-').reverse().join('-');
 const timeText=String(r?.HoraReserva||'').slice(0,5);
 const createdText=created?formatPdfDateTime(created):'';
 const generatedText=formatPdfDateTime(generated.toISOString());
 const w=window.open('','_blank');
 if(!w)return false;
 const logo='./logocamborio_trans.png';
 const esc=escapeHtml;
 w.document.open();
 w.document.write(`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Reserva ${esc(r?.CodigoReserva||'')}</title><style>
 @page{size:A4;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff;color:#17202d;font-family:Arial,Helvetica,sans-serif}.page{width:210mm;min-height:297mm;padding:11mm 15.5mm 13mm;position:relative}.header{height:59mm;position:relative;border-bottom:1.1mm solid #e5a500}.header-logo{position:absolute;left:5mm;top:2mm;width:42mm;height:42mm;object-fit:contain}.header-center{margin-left:48mm;width:132mm;text-align:center;padding-top:7mm}.header-title{font-family:Georgia,'Times New Roman',serif;font-size:27px;line-height:1.08;font-weight:700;letter-spacing:1.1px;color:#6e2d16;white-space:nowrap}.header-sub{display:flex;align-items:center;justify-content:center;gap:5mm;margin-top:3mm;color:#0f6331;font-family:Georgia,'Times New Roman',serif;font-size:17px;font-weight:700;letter-spacing:1.1px;white-space:nowrap}.header-sub:before,.header-sub:after{content:"";width:12mm;height:.55mm;background:#d99b00}.header-address{font-size:11px;margin-top:3mm}.header-phone{font-size:11px;margin-top:1.5mm}.header-phone strong{color:#146b37}.pdf-title{text-align:center;font-size:18px;font-weight:800;letter-spacing:1.1px;margin-top:5.5mm}.code-box{width:150mm;height:17mm;margin:3mm auto 4.5mm;border:1px solid #176936;border-radius:3mm;display:flex;align-items:center;justify-content:center;color:#0d672e;font-size:29px;font-weight:800;letter-spacing:6px}.details{border:1px solid #d7dde4;border-radius:3mm;overflow:hidden}.row{display:grid;grid-template-columns:41% 59%;min-height:9.8mm;border-bottom:1px solid #dce1e7;align-items:center;font-size:11px}.row:last-child{border-bottom:0}.label{font-weight:800;padding-left:4mm}.value{padding-left:2mm}.status{display:inline-block;border:1px solid #e3a900;border-radius:2.2mm;padding:1.8mm 3mm;color:#1b6134;font-weight:800}.notice{border:1px solid #e3a900;border-radius:3mm;padding:4.5mm 4.5mm 4mm;margin-top:4.5mm}.notice strong{display:block;font-size:13.5px;line-height:1.35}.notice p{margin:2mm 0 0;font-size:11px}.consult{border:1px solid #176936;border-radius:3mm;padding:4.5mm 4.5mm 4mm;margin-top:4mm}.consult strong{display:block;color:#166a36;font-size:13.5px;line-height:1.2}.consult p{margin:2mm 0 1mm;font-size:11px}.consult .line{font-size:11px;margin-top:1.2mm}.consult b{color:#166a36}.footer{position:absolute;left:15.5mm;right:15.5mm;bottom:29mm;border-top:1px solid #176936;text-align:center;padding-top:4mm}.footer strong{font-size:12px}.footer small{display:block;font-size:8.5px;margin-top:2.5mm}.nowrap{white-space:nowrap}
 </style></head><body><main class="page"><header class="header"><img class="header-logo" src="${logo}" alt="Taberna Camborio"><div class="header-center"><div class="header-title">TABERNA CAMBORIO</div><div class="header-sub">CERVECERÍA - TAPERÍA</div><div class="header-address">Calle Real, 184 - 11100 San Fernando</div><div class="header-phone">Teléfono: <strong>956 25 45 32</strong></div></div></header><div class="pdf-title">CÓDIGO DE RESERVA</div><div class="code-box">${esc(r?.CodigoReserva||'-')}</div><section class="details"><div class="row"><div class="label">Nombre</div><div class="value">${esc(r?.Nombre||'')}</div></div><div class="row"><div class="label">Teléfono</div><div class="value">${esc(r?.Telefono||'')}</div></div><div class="row"><div class="label">Email</div><div class="value">${esc(r?.Email||'')}</div></div><div class="row"><div class="label">Fecha</div><div class="value">${esc(dateText)}</div></div><div class="row"><div class="label">Hora</div><div class="value">${esc(timeText)}</div></div><div class="row"><div class="label">Personas</div><div class="value">${esc(r?.Personas??'')}</div></div><div class="row"><div class="label">Estado</div><div class="value"><span class="status">${esc(r?.Estado||'PENDIENTE DE CONFIRMACIÓN')}</span></div></div><div class="row"><div class="label">Observaciones</div><div class="value">${esc(r?.Observaciones||'Sin observaciones')}</div></div></section><section class="notice"><strong>ESTA RESERVA ESTÁ PENDIENTE DE CONFIRMACIÓN POR EL RESTAURANTE.</strong><p>En cuanto sea confirmada, podrás consultar el estado actual.</p></section><section class="consult"><strong>PUEDE CONSULTAR EL ESTADO DE SU RESERVA</strong><p>Puede consultar el estado actual de su reserva entrando con:</p><div class="line">Teléfono: <b>${esc(r?.Telefono||'')}</b></div><div class="line">Código de reserva: <b>${esc(r?.CodigoReserva||'')}</b></div></section><footer class="footer"><strong>Gracias por reservar en Taberna Camborio.</strong><small>Documento generado el ${esc(generatedText)}${createdText?` · Reserva creada ${esc(createdText)}`:''}</small></footer></main><script>window.addEventListener('load',()=>setTimeout(()=>window.print(),250));<\/script></body></html>`);
 w.document.close();
 return true;
}
function formatPdfDateTime(v){const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return d.toLocaleDateString('es-ES',{day:'2-digit',month:'2-digit',year:'numeric'})+' a las '+d.toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});}
function install(){
 ensureModal();
 $('date').onclick=()=>openDateModal('date');$('edit-date').onclick=()=>openDateModal('edit-date');$('date-prev').onclick=()=>changeMonth(-1);$('date-next').onclick=()=>changeMonth(1);$('date-cancel').onclick=closeDateModal;$('date-modal-close').onclick=closeDateModal;
 $('time-trigger').onclick=e=>{e.preventDefault();openTimes(false)};$('edit-time-trigger').onclick=e=>{e.preventDefault();openTimes(true)};
 $('reservation-form').onsubmit=e=>{e.preventDefault();if(!validForm())return;renderSummary();showScreen('screen-confirm')};
 $('back-button').onclick=()=>showScreen('screen-form');$('finish-button').onclick=()=>showScreen('screen-thanks');$('existing-button').onclick=()=>showScreen('screen-consult');$('consult-back').onclick=()=>showScreen('screen-form');$('found-edit').onclick=()=>showScreen('screen-edit');$('found-back').onclick=()=>showScreen('screen-consult');$('edit-back').onclick=()=>showScreen('screen-found');
 $('received-pdf').onclick=()=>{const r=window.__publicReservation||window.__v4Reservation;if(!r)return info('No se ha encontrado la reserva para generar el justificante.',{title:'Justificante',icon:'📄'});if(!buildReservationPdf(r))info('El navegador bloqueó la ventana del justificante.',{title:'Justificante',icon:'📄'})};
 $('email-close').onclick=closeEmailModal;$('email-cancel').onclick=closeEmailModal;$('email-modal-close').onclick=closeEmailModal;$('received-email').onclick=openEmailModal;$('found-email').onclick=openEmailModal;
 setDateField('date','');setDateField('edit-date','');
 document.addEventListener('click',e=>{const id=e.target.closest('button')?.id;if(id!=='found-cancel'&&id!=='cancel-reservation')return;e.preventDefault();e.stopImmediatePropagation();const r=window.__publicReservation||window.__v4Reservation;if(!r)return;(async()=>{const ok=await info('¿Quieres cancelar esta reserva? Esta acción no se puede deshacer desde la PWA.',{title:'Cancelar reserva',icon:'⚠️',confirm:true,ok:'CANCELAR RESERVA'});if(!ok)return;try{const res=await fetch(API(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cancel',telefono:r.Telefono,codigo:r.CodigoReserva})});const d=await res.json();if(!res.ok||d.ok===false)throw new Error(d.error||'No se ha podido cancelar la reserva.');window.__publicReservation=d.reservation;showScreen('screen-thanks');await info('La reserva se ha cancelado correctamente.',{title:'Reserva cancelada',icon:'✓'})}catch(err){info(err.message,{title:'No se pudo cancelar',icon:'⚠️'})}})()},true);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();

if('serviceWorker' in navigator){
 window.addEventListener('load',()=>{
  navigator.serviceWorker.register('./sw.js').catch(()=>{});
 });
}
