(function(){'use strict';
const C=window.CAMBORIO_CONFIG||{};const API=C.publicReservationsFunction;const EMAIL_API=C.emailFunction;if(!API)return;const $=id=>document.getElementById(id);const state=window.state||null;
async function call(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});let d=null;try{d=await r.json()}catch{}if(!r.ok||!d?.ok)throw new Error(d?.error||'No se ha podido completar la operación.');return d}
function publicUrl(){return window.location.origin+window.location.pathname}
async function sendEmail(payload){if(!EMAIL_API)throw new Error('El servicio de correo no está configurado.');const r=await fetch(EMAIL_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let d=null;try{d=await r.json()}catch{}if(!r.ok||!d?.ok)throw new Error(d?.error||'No se ha podido enviar el correo.');return d}
function showError(e){alert(e?.message||'Ha ocurrido un error.');}
function copyReservation(r){if(!r)return;window.__publicReservation=r;if(window.state){Object.assign(window.state,{name:r.Nombre||'',phone:r.Telefono||'',email:r.Email||'',people:String(r.Personas||''),date:r.FechaReserva||'',time:String(r.HoraReserva||'').slice(0,5),notes:r.Observaciones||'',code:r.CodigoReserva||''})}}
function renderFound(r){copyReservation(r);const rows=[['👤 Nombre',r.Nombre||'-'],['📞 Teléfono',r.Telefono||'-'],['✉️ Email',r.Email||'-'],['👥 Comensales',r.Personas??'-'],['📅 Fecha',r.FechaReserva||'-'],['🕘 Hora',String(r.HoraReserva||'').slice(0,5)||'-'],['📝 Observaciones',r.Observaciones||'Sin observaciones'],['📌 Estado',r.Estado||'-']];const box=$('found-summary');if(box)box.innerHTML=rows.map(x=>`<div class="summary-row"><span class="summary-label">${x[0]}</span><span class="summary-value">${String(x[1]).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]))}</span></div>`).join('');if($('edit-code'))$('edit-code').textContent=r.CodigoReserva||'';if($('reservation-code'))$('reservation-code').textContent=r.CodigoReserva||'';if($('edit-name'))$('edit-name').value=r.Nombre||'';if($('edit-phone'))$('edit-phone').value=r.Telefono||'';if($('edit-email'))$('edit-email').value=r.Email||'';if($('edit-people'))$('edit-people').value=r.Personas??'';if($('edit-notes'))$('edit-notes').value=r.Observaciones||'';if(typeof setDateField==='function')setDateField('edit-date',r.FechaReserva||'');if($('edit-selected-time'))$('edit-selected-time').textContent=String(r.HoraReserva||'').slice(0,5);if($('edit-time-trigger'))$('edit-time-trigger').classList.toggle('has-time',!!r.HoraReserva)}
async function create(){try{const b={nombre:$('name').value.trim(),telefono:$('phone').value.trim(),email:$('email').value.trim(),personas:Number($('people').value),fecha:$('date').dataset.iso||'',hora:window.state?.time||'',observaciones:$('notes').value.trim()};const d=await call('create',b);copyReservation(d.reservation);if(d.reservation?.Email){try{await sendEmail({telefono:d.reservation.Telefono,codigo:d.reservation.CodigoReserva,publicUrl:publicUrl()});}catch(e){console.error('No se pudo enviar la confirmación por Gmail:',e);}}if($('reservation-code'))$('reservation-code').textContent=d.reservation.CodigoReserva;showScreen('screen-received')}catch(e){showError(e)}}
async function lookup(){try{const phone=$('lookup-phone').value.trim(),code=$('lookup-code').value.trim();if(!phone||!code){showError(new Error('Introduce teléfono y código de reserva.'));return}const d=await call('lookup',{telefono:phone,codigo:code});if(!d.reservation){showError(new Error('No se ha encontrado ninguna reserva con esos datos.'));return}renderFound(d.reservation);showScreen('screen-found')}catch(e){showError(e)}}
async function cancel(r){try{const d=await call('cancel',{telefono:r.Telefono,codigo:r.CodigoReserva});renderFound(d.reservation);showScreen('screen-thanks')}catch(e){showError(e)}}
async function update(){try{const r=window.__publicReservation||{};const b={telefono:r.Telefono||$('edit-phone').value.trim(),codigo:r.CodigoReserva||$('edit-code').textContent.trim(),nombre:$('edit-name').value.trim(),email:$('edit-email').value.trim(),personas:Number($('edit-people').value),fecha:$('edit-date').dataset.iso||'',hora:$('edit-selected-time').textContent.trim(),observaciones:$('edit-notes').value.trim()};if(!b.fecha||!/^\d{1,2}:\d{2}$/.test(b.hora))throw new Error('Selecciona fecha y hora.');const d=await call('update',b);renderFound(d.reservation);showScreen('screen-thanks')}catch(e){showError(e)}}
async function email(){try{const r=window.__publicReservation||{};const dest=$('email-send').value.trim();if(!dest)throw new Error('Introduce un email.');await sendEmail({telefono:r.Telefono,codigo:r.CodigoReserva,email:dest,publicUrl:publicUrl()});closeEmailModal();alert('Correo enviado correctamente.')}catch(e){showError(e)}}
$('confirm-button').onclick=create;$('lookup-button').onclick=lookup;$('found-cancel').onclick=()=>{const r=window.__publicReservation;if(!r)return;if(confirm('¿Quieres cancelar esta reserva?'))cancel(r)};$('cancel-reservation').onclick=()=>{const r=window.__publicReservation;if(!r)return;if(confirm('¿Quieres cancelar esta reserva?'))cancel(r)};$('edit-form').onsubmit=e=>{e.preventDefault();update()};$('email-form').onsubmit=e=>{e.preventDefault();email()};
})();
