(function(){'use strict';
let loading=null;
const $=id=>document.getElementById(id);
const text=v=>String(v==null?'':v).trim();
const esc=v=>text(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
function load(){if(window.html2pdf)return Promise.resolve(window.html2pdf);if(loading)return loading;loading=new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js';s.onload=()=>window.html2pdf?ok(window.html2pdf):no(Error('Generador PDF no disponible'));s.onerror=()=>no(Error('No se pudo cargar el generador PDF'));document.head.appendChild(s)});return loading}
function fmtDate(v){const m=text(v).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?m[3]+'-'+m[2]+'-'+m[1]:text(v)}
function fmtTime(v){const m=text(v).match(/(?:T|\s|^)(\d{1,2}):(\d{2})/);return m?m[1].padStart(2,'0')+':'+m[2]:text(v).slice(0,5)}
function html(r){r=r||{};const estado=text(r.Estado).toUpperCase();const estados={PENDIENTE:'Pendiente de confirmación',CONFIRMADA:'Confirmada',SENTADA:'Sentada',FINALIZADA:'Finalizada',CANCELADA_CLIENTE:'Cancelada por el cliente',CANCELADA_LOCAL:'Cancelada por el restaurante',NO_PRESENTADO:'No presentado'};const estadoTexto=estados[estado]||estado||'Pendiente de confirmación';return '<!doctype html><html><head><meta charset="utf-8"><style>*{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff}body{width:794px;font-family:Arial,sans-serif;color:#111827;font-size:14px;padding:34px}.head{text-align:center;border-bottom:4px solid #f2a100;padding-bottom:18px}.brand{font:700 34px Georgia,serif;letter-spacing:2px;color:#5b260f}.sub{font:700 20px Georgia,serif;letter-spacing:2px;color:#0d5a22;margin-top:8px}.muted{margin-top:6px}.code-title{text-align:center;font-size:20px;font-weight:800;margin:24px 0 10px}.code{border:2px solid #0d5a22;border-radius:8px;color:#0d5a22;text-align:center;font-size:38px;font-weight:900;letter-spacing:7px;padding:12px;margin-bottom:22px}.data{width:100%;border-collapse:collapse;border:1px solid #d7dde5}.data th,.data td{border-bottom:1px solid #e2e6ec;padding:12px;text-align:left}.data th{width:34%;background:#f7f8fa}.badge{font-weight:800;border:1px solid #0d5a22;border-radius:7px;padding:6px 10px}.notice,.lookup{margin-top:18px;padding:14px 16px;border-radius:9px}.notice{border:1px solid #f2a100;background:#fffdf2}.lookup{border:1px solid #0d5a22;background:#f3fbf5}.footer{margin-top:26px;padding-top:14px;border-top:1px solid #0d5a22;text-align:center;font-weight:800}.version{text-align:center;font-size:10px;color:#6b7280;margin-top:8px}</style></head><body><div class="head"><div class="brand">TABERNA CAMBORIO</div><div class="sub">Cervecería - Tapería</div><div class="muted">Calle Real, 184 - 11100 San Fernando</div><div class="muted">Teléfono: <b>956 25 45 32</b></div></div><div class="code-title">CÓDIGO DE RESERVA</div><div class="code">'+esc(r.CodigoReserva||'-')+'</div><table class="data"><tr><th>Nombre</th><td>'+esc(r.Nombre||'-')+'</td></tr><tr><th>Teléfono</th><td>'+esc(r.Telefono||'-')+'</td></tr><tr><th>Email</th><td>'+esc(r.Email||'-')+'</td></tr><tr><th>Fecha</th><td>'+esc(fmtDate(r.FechaReserva)||'-')+'</td></tr><tr><th>Hora</th><td>'+esc(fmtTime(r.HoraReserva)||'-')+'</td></tr><tr><th>Personas</th><td>'+esc(r.Personas||'-')+'</td></tr><tr><th>Estado</th><td><span class="badge">'+esc(estadoTexto)+'</span></td></tr><tr><th>Observaciones</th><td>'+esc(r.Observaciones||'Sin observaciones')+'</td></tr></table><div class="notice">Esta reserva está: <b>'+esc(estadoTexto)+'</b></div><div class="lookup"><b>Consulta de reserva</b><br>Teléfono: <b>'+esc(r.Telefono||'-')+'</b><br>Código: <b>'+esc(r.CodigoReserva||'-')+'</b></div><div class="footer">Gracias por reservar en Taberna Camborio.</div><div class="version">Camborio Reservas V4 · PDF 2026-09-14.2</div></body></html>'}
async function generate(r){if(!r)throw Error('No se ha encontrado la reserva');const pdf=await load();const holder=document.createElement('div');holder.innerHTML=html(r);holder.setAttribute('aria-hidden','true');Object.assign(holder.style,{position:'fixed',left:'0',top:'0',width:'794px',height:'1123px',overflow:'hidden',opacity:'0.01',visibility:'visible',zIndex:'-1',background:'#fff',pointerEvents:'none'});document.body.appendChild(holder);try{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));await pdf().set({filename:'Reserva_'+(text(r.CodigoReserva)||'Camborio')+'.pdf',margin:0,image:{type:'jpeg',quality:1},html2canvas:{scale:2,backgroundColor:'#fff,useCORS':false,allowTaint:false,logging:false,windowWidth:794,windowHeight:1123,scrollX:0,scrollY:0},jsPDF:{unit:'pt',format:'a4',orientation:'portrait'},pagebreak:{mode:['css']}}).from(holder).save()}finally{holder.remove()}}
function run(r){const bs=[...document.querySelectorAll('#received-pdf,#found-pdf,#edit-pdf')];bs.forEach(b=>b.disabled=true);generate(r).catch(e=>{console.error(e);alert('No se pudo generar el PDF. '+e.message)}).finally(()=>bs.forEach(b=>b.disabled=false))}
function bind(){const r=()=>window.__publicReservation||window.__v4Reservation;document.addEventListener('click',e=>{const b=e.target.closest('#received-pdf,#found-pdf,#edit-pdf');if(!b)return;e.preventDefault();e.stopImmediatePropagation();run(r())},true)}
window.buildReservationPdf=generate;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();