(function(){
'use strict';
const $=id=>document.getElementById(id);
const LOGO_URL='https://caeszgtogifserrxdrcw.supabase.co/storage/v1/object/public/camborio-assets/logocamborio_trans.png?v=20260904';
const LUNCH=['12:30','12:45','13:00','13:15','13:30','13:45','14:00','14:15','14:30','14:45','15:00'];
const DINNER=['20:30','20:45','21:00','21:15','21:30','21:45','22:00','22:15','22:30','22:45','23:00'];
const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function madridMinutes(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());let h=0,m=0;p.forEach(x=>{if(x.type==='hour')h=+x.value;if(x.type==='minute')m=+x.value});return h*60+m}
function ensureTimes(id,values,select){const box=$(id);if(!box)return;box.innerHTML='';values.forEach(time=>{const b=document.createElement('button');b.type='button';b.className='time-btn';b.textContent=time;b.addEventListener('click',()=>select(time,b));box.appendChild(b)})}
function applyAvailability(lunchId,dinnerId,dateId){const date=$(dateId)?.dataset.iso;if(!date)return;const now=date===todayISO()?madridMinutes():-1;[lunchId,dinnerId].forEach(id=>{const box=$(id);if(!box)return;box.querySelectorAll('.time-btn').forEach(b=>{const parts=String(b.textContent).split(':').map(Number);const mins=parts.length===2?parts[0]*60+parts[1]:-1;const past=now>=0&&mins>=0&&mins<=now;b.hidden=past;b.disabled=past})})}
function selectMainTime(time,b){const label=$('selected-time');const trigger=$('time-trigger');if(label)label.textContent=time;if(trigger)trigger.classList.add('has-time');document.querySelectorAll('#time-panel .time-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('time-panel').hidden=true;if(window.state)window.state.time=time}
function selectEditTime(time,b){const label=$('edit-selected-time');const trigger=$('edit-time-trigger');if(label)label.textContent=time;if(trigger)trigger.classList.add('has-time');document.querySelectorAll('#edit-time-panel .time-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('edit-time-panel').hidden=true;if(window.state)window.state.time=time}
function openTime(panelId,dateId,lunchId,dinnerId){const date=$(dateId),panel=$(panelId);if(!date?.dataset.iso){showInfo('Selecciona primero una fecha.','Fecha necesaria');return}applyAvailability(lunchId,dinnerId,dateId);const available=panel?.querySelectorAll('.time-btn:not([hidden])').length||0;if(panel&&available>0)panel.hidden=false;else if(panel)showInfo('No quedan horas disponibles para ese día.','Sin horas disponibles')}
function showInfo(message,title='Información'){let modal=$('v4-info-modal');if(!modal){modal=document.createElement('div');modal.id='v4-info-modal';modal.className='v4-dialog';modal.hidden=true;modal.innerHTML='<div class="v4-dialog-backdrop"></div><div class="v4-dialog-card" role="dialog" aria-modal="true"><div class="v4-dialog-icon">ⓘ</div><h2></h2><p></p><button type="button">ACEPTAR</button></div>';document.body.appendChild(modal);modal.querySelector('.v4-dialog-backdrop').onclick=()=>closeInfo();modal.querySelector('button').onclick=()=>closeInfo()}modal.querySelector('h2').textContent=title;modal.querySelector('p').textContent=message;modal.hidden=false;setTimeout(()=>modal.querySelector('button').focus(),20)}
function closeInfo(){const m=$('v4-info-modal');if(m)m.hidden=true}
function showConfirm(message,title,onYes){let modal=$('v4-confirm-modal');if(!modal){modal=document.createElement('div');modal.id='v4-confirm-modal';modal.className='v4-dialog';modal.hidden=true;modal.innerHTML='<div class="v4-dialog-backdrop"></div><div class="v4-dialog-card" role="dialog" aria-modal="true"><div class="v4-dialog-icon">?</div><h2></h2><p></p><div class="v4-dialog-actions"><button type="button" data-no>CANCELAR</button><button type="button" data-yes>CONFIRMAR</button></div></div>';document.body.appendChild(modal);modal.querySelector('.v4-dialog-backdrop').onclick=()=>modal.hidden=true;modal.querySelector('[data-no]').onclick=()=>modal.hidden=true}modal.querySelector('h2').textContent=title;modal.querySelector('p').textContent=message;modal.querySelector('[data-yes]').onclick=()=>{modal.hidden=true;onYes()};modal.hidden=false;setTimeout(()=>modal.querySelector('[data-yes]').focus(),20)}
function installDialogs(){const s=document.createElement('style');s.textContent=`.v4-dialog[hidden]{display:none!important}.v4-dialog{position:fixed!important;inset:0!important;z-index:9999!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:18px!important}.v4-dialog-backdrop{position:absolute!important;inset:0!important;background:rgba(8,12,17,.72)!important}.v4-dialog-card{position:relative!important;z-index:1!important;width:min(92vw,360px)!important;background:#20252b!important;color:#f1f3f5!important;border:1px solid #3b444e!important;border-radius:22px!important;padding:22px 18px 16px!important;box-shadow:0 18px 50px rgba(0,0,0,.45)!important;text-align:center!important}.v4-dialog-icon{width:44px!important;height:44px!important;margin:0 auto 9px!important;border-radius:50%!important;background:#2a3037!important;color:#ffca19!important;display:grid!important;place-items:center!important;font-size:25px!important;font-weight:800!important}.v4-dialog-card h2{margin:0 0 7px!important;font-size:18px!important}.v4-dialog-card p{margin:0 5px 16px!important;color:#b8c0c9!important;font-size:13px!important;line-height:1.4!important}.v4-dialog-card>button,.v4-dialog-actions button{min-height:40px!important;border-radius:10px!important;padding:0 18px!important;border:1px solid #48515c!important;background:#2a3037!important;color:#f1f3f5!important;font-weight:800!important}.v4-dialog-actions{display:flex!important;gap:8px!important;justify-content:center!important}.v4-dialog-actions button:last-child{background:#ffca19!important;border-color:#ffca19!important;color:#111820!important}`;document.head.appendChild(s)}
function install(){installDialogs();const mark=document.querySelector('.brand-mark');if(mark){mark.src=LOGO_URL;mark.removeAttribute('srcset');mark.style.backgroundImage='none';mark.style.backgroundColor='transparent';mark.style.objectFit='contain'}
const panel=$('time-panel'),editPanel=$('edit-time-panel');
ensureTimes('lunch-times',LUNCH,selectMainTime);ensureTimes('dinner-times',DINNER,selectMainTime);ensureTimes('edit-lunch-times',LUNCH,selectEditTime);ensureTimes('edit-dinner-times',DINNER,selectEditTime);
if(panel)panel.hidden=true;if(editPanel)editPanel.hidden=true;
const tb=$('time-trigger');if(tb){tb.onclick=e=>{e.preventDefault();if(panel&&!panel.hidden){panel.hidden=true;return}openTime('time-panel','date','lunch-times','dinner-times')}}
const et=$('edit-time-trigger');if(et){et.onclick=e=>{e.preventDefault();if(editPanel&&!editPanel.hidden){editPanel.hidden=true;return}openTime('edit-time-panel','edit-date','edit-lunch-times','edit-dinner-times')}}
const d=$('date');if(d)d.onclick=e=>{e.preventDefault();if(typeof openDateModal==='function')openDateModal('date')};const ed=$('edit-date');if(ed)ed.onclick=e=>{e.preventDefault();if(typeof openDateModal==='function')openDateModal('edit-date')};
const grid=$('date-grid');if(grid){const obs=new MutationObserver(()=>grid.querySelectorAll('.date-day').forEach(b=>{if(b.dataset.v4Bound)return;b.dataset.v4Bound='1';b.addEventListener('click',()=>setTimeout(()=>{if(window.calendarTarget==='date'&&panel)panel.hidden=true;if(window.calendarTarget==='edit-date'&&editPanel)editPanel.hidden=true},0))}));obs.observe(grid,{childList:true})}
const receivedPdf=$('received-pdf');if(receivedPdf)receivedPdf.onclick=e=>{e.preventDefault();showInfo('La descarga del PDF estará disponible cuando esté conectada la generación de documentos.','PDF')};
const emailForm=$('email-form');if(emailForm)emailForm.onsubmit=e=>{e.preventDefault();const input=$('email-send');if(!input?.checkValidity()){input?.reportValidity();return}if(typeof closeEmailModal==='function')closeEmailModal();showInfo('El servicio de correo todavía no está conectado.','Email')};
const foundCancel=$('found-cancel');if(foundCancel)foundCancel.onclick=e=>{e.preventDefault();showConfirm('¿Quieres cancelar esta reserva?','Cancelar reserva',()=>{showInfo('La solicitud de cancelación ha sido registrada.','Reserva cancelada');setTimeout(()=>showScreen('screen-thanks'),900)})};
const editCancel=$('cancel-reservation');if(editCancel)editCancel.onclick=e=>{e.preventDefault();showConfirm('¿Quieres cancelar esta reserva?','Cancelar reserva',()=>{showInfo('La solicitud de cancelación ha sido registrada.','Reserva cancelada');setTimeout(()=>showScreen('screen-thanks'),900)})};
const editForm=$('edit-form');if(editForm){editForm.addEventListener('submit',e=>{e.preventDefault();if(!$('edit-form').checkValidity()){$('edit-form').reportValidity();return}if(!$('edit-date').dataset.iso){showInfo('Selecciona primero una fecha.','Fecha necesaria');return}if(!$('edit-selected-time').textContent||$('edit-selected-time').textContent==='Selecciona una hora'){showInfo('Selecciona una hora para continuar.','Hora necesaria');return}showInfo('Los cambios se han guardado correctamente.','Reserva actualizada')})}
const form=$('reservation-form');if(form){form.addEventListener('submit',e=>{if(!$('date').dataset.iso){e.preventDefault();showInfo('Selecciona primero una fecha.','Fecha necesaria');return}if(!$('selected-time').textContent||$('selected-time').textContent==='Selecciona una hora'){e.preventDefault();showInfo('Selecciona una hora para continuar.','Hora necesaria');return}},true)}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();