(function(){
'use strict';
const $=id=>document.getElementById(id);
const LOGO_URL='https://caeszgtogifserrxdrcw.supabase.co/storage/v1/object/public/camborio-assets/logocamborio_trans.png?v=20260902';
const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function madridMinutes(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());let h=0,m=0;p.forEach(x=>{if(x.type==='hour')h=+x.value;if(x.type==='minute')m=+x.value});return h*60+m}
function applyAvailability(lunchId,dinnerId,dateId){const date=$(dateId)?.dataset.iso;if(!date)return;const now=date===todayISO()?madridMinutes():-1;[lunchId,dinnerId].forEach(id=>{const box=$(id);if(!box)return;box.querySelectorAll('.time-btn').forEach(b=>{const a=String(b.textContent||'').trim().split(':');const mins=a.length===2?(+a[0]*60+ +a[1]):-1;b.hidden=now>=0&&mins>=0&&mins<=now;b.disabled=b.hidden})})}
function openTime(panelId,dateId,lunchId,dinnerId){const date=$(dateId),panel=$(panelId);if(!date?.dataset.iso){if(typeof openDateModal==='function')openDateModal(dateId);return}applyAvailability(lunchId,dinnerId,dateId);if(panel)panel.hidden=false}
function install(){const s=document.createElement('style');s.textContent=`.brand-mark{background-image:none!important;background-color:transparent!important;object-fit:contain!important}.time-panel[hidden]{display:none!important}.time-panel{width:100%!important;margin-top:6px!important}.time-panel .time-grid{display:grid!important}.time-panel .time-btn[hidden]{display:none!important}.date-modal[hidden]{display:none!important}.date-modal{position:static!important;inset:auto!important;background:transparent!important;padding:0!important;width:100%!important}.date-modal-card{position:relative!important;width:100%!important;max-width:100%!important;margin:8px 0 10px!important;padding:8px 10px!important;border-radius:10px!important;box-shadow:none!important}.weekdays,.date-grid{gap:2px!important}.date-day,.date-empty{width:32px!important;height:32px!important;font-size:13px!important}`;document.head.appendChild(s);
const mark=document.querySelector('.brand-mark');if(mark){mark.src=LOGO_URL;mark.removeAttribute('srcset');mark.style.backgroundImage='none';mark.style.backgroundColor='transparent';mark.style.objectFit='contain'}
const tb=$('time-trigger');if(tb)tb.onclick=e=>{e.preventDefault();const p=$('time-panel');if(!p)return;if(!p.hidden){p.hidden=true;return}openTime('time-panel','date','lunch-times','dinner-times')};
const et=$('edit-time-trigger');if(et)et.onclick=e=>{e.preventDefault();const p=$('edit-time-panel');if(!p)return;if(!p.hidden){p.hidden=true;return}openTime('edit-time-panel','edit-date','edit-lunch-times','edit-dinner-times')};
const d=$('date');if(d)d.onclick=e=>{e.preventDefault();if(typeof openDateModal==='function')openDateModal('date')};
const ed=$('edit-date');if(ed)ed.onclick=e=>{e.preventDefault();if(typeof openDateModal==='function')openDateModal('edit-date')};
const grid=$('date-grid');if(grid){const obs=new MutationObserver(()=>grid.querySelectorAll('.date-day').forEach(b=>{if(b.dataset.v4Bound)return;b.dataset.v4Bound='1';b.addEventListener('click',()=>setTimeout(()=>{const id=window.calendarTarget==='date'?'time-panel':'edit-time-panel';if($(id))$(id).hidden=true},0))}));obs.observe(grid,{childList:true})}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();