(function(){
'use strict';
const $=id=>document.getElementById(id);
const lunch=['12:30','12:45','13:00','13:15','13:30','13:45','14:00','14:15','14:30','14:45','15:00'];
const dinner=['20:30','20:45','21:00','21:15','21:30','21:45','22:00','22:15','22:30','22:45','23:00'];
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function madridMinutes(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());let h=0,m=0;p.forEach(x=>{if(x.type==='hour')h=+x.value;if(x.type==='minute')m=+x.value});return h*60+m}
function future(list,date){if(date!==today())return list;const now=madridMinutes();return list.filter(t=>{const [h,m]=t.split(':').map(Number);return h*60+m>now})}
function paint(id,list,selected,cb){const box=$(id);if(!box)return;box.innerHTML='';list.forEach(t=>{const b=document.createElement('button');b.type='button';b.className='time-btn';b.textContent=t;if(t===selected)b.classList.add('selected');b.onclick=()=>cb(t,b);box.appendChild(b)})}
function refreshPublicHours(){const f=$('date');if(!f||!f.dataset.iso)return;const d=f.dataset.iso;const ls=future(lunch,d),ds=future(dinner,d);const selected=$('selected-time')?.textContent;paint('lunch-times',ls,selected,(t,b)=>{window.__v4SelectTime(t,b)});paint('dinner-times',ds,selected,(t,b)=>{window.__v4SelectTime(t,b)});}
window.__v4SelectTime=function(t,b){const f=$('date');if(!f||!f.dataset.iso)return;window.__v4SelectedTime=t; if(window.state)window.state.time=t;if($('selected-time'))$('selected-time').textContent=t;if($('time-trigger'))$('time-trigger').classList.add('has-time');document.querySelectorAll('#time-panel .time-btn').forEach(x=>x.classList.remove('selected'));if(b)b.classList.add('selected');if($('time-panel'))$('time-panel').hidden=true};
function compact(){const s=document.createElement('style');s.textContent='.date-modal[hidden]{display:none!important}.date-modal{position:static!important;inset:auto!important;background:transparent!important;padding:0!important;width:100%!important;display:block!important}.date-modal-card{position:relative!important;width:100%!important;max-width:100%!important;margin:8px 0 10px!important;padding:8px 10px!important;border-radius:10px!important;box-shadow:none!important}.date-modal-head{margin-bottom:5px!important}.date-modal-head button{width:34px!important;height:34px!important}.weekdays,.date-grid{gap:2px!important}.date-day,.date-empty{width:32px!important;height:32px!important;font-size:13px!important}.date-modal-actions{margin-top:5px!important}.date-modal-actions button{min-height:34px!important;font-size:13px!important}';document.head.appendChild(s)}
function wire(){compact();const tb=$('time-trigger');if(tb)tb.onclick=function(){const f=$('date');if(!f||!f.dataset.iso){if($('date'))$('date').focus();return}refreshPublicHours();$('time-panel').hidden=!$('time-panel').hidden};const date=$('date');if(date){date.addEventListener('change',refreshPublicHours);date.addEventListener('input',refreshPublicHours)}const modal=$('date-modal');if(modal){const observer=new MutationObserver(()=>{if(modal.hidden)return;const grid=$('date-grid');if(!grid)return;grid.querySelectorAll('.date-day:not([disabled])').forEach(b=>{b.addEventListener('click',()=>setTimeout(refreshPublicHours,0),{once:true})})});observer.observe(modal,{attributes:true,subtree:true,childList:true});}if($('reservation-form'))$('reservation-form').addEventListener('submit',()=>{if(!$('date')?.dataset.iso){return}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
